### PR TITLE
Upgrade OpenLayers from `v6.1.1` to `v8.2.0`

### PR DESCRIPTION
**Pull request by JakobMiksch**
- only minor code adaptation was needed to perform the upgrade
- upgrade should not change anything in the UI
- change source of OpenLayers library  from https://openlayers.org to https://cdn.jsdelivr.net was needed, because the OpenLayers website does not seem to provide the library anymore
- the webmap in the `pgrouting` example also still works after the upgrade: https://github.com/CrunchyData/pg_featureserv/blob/master/demo/routing/openlayers-pgrouting.html

### CODE REVIEW

**Comment by dr-jts** [comment]
Perhaps OpenLayers should just be vendored in, to avoid external dependencies?

**Comment by JakobMiksch** [comment]
> Perhaps OpenLayers should just be vendored in, to avoid external dependencies?

@dr-jts True, how would you prefer to do that?
I see these options:
- add a minified version of the OL library (+CSS) to the git of the project. It has the advantage, that pg_featureserv can start immediately, but checking in a dependency in to git is not always preferred
- the OL library (+CSS) needs to be downloaded when the program is built or it has do be done (semi-)manually by the person who starts a local dev setup. we might night a little script for that (or maybe go has some inbuilt functionality (?) )

**Comment by JakobMiksch** [comment]
@dr-jts I upgraded this PR to OpenLayers `8.2.0`. 
I like the idea of keeping the library of OpenLayers directly in pg_feature. However, I think this should be a separate issue.
What do you think, can we merge this PR?

**Comment by JakobMiksch** [comment]
closed for same reasons as #147

**Pull request closed without merging**
