### PR TITLE
Map view: ensure data extent is set on start

### PR DESCRIPTION
**Pull request by JakobMiksch**
- before when the map was loaded the extent was initially at null island and jumped afterwards to the extent of the data. see GIFs below. I find this a bit distracting and confusing.
- this PR ensures the map has the data extent directly at the start by loading the data first and initializing the map afterwards
- for loading the data the very ancient [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest) was chosen to guarantee maximum browser compatibility. However we could also use the more modern [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch) approach. 

**before:**

ol-before

**after:**

ol_after

### CODE REVIEW

**Comment by dr-jts** [comment]
What if the data takes a long time to load, or errors out?

**Comment by JakobMiksch** [comment]
- loading the in-built example with 10000 points loads in reasonable time (a few seconds):

Peek 2023-10-21 16-02

- when I add a 5 second timeout in the JavaScript code, the website stays white until there is data to display, see here:

timeout

- I have not simulated a complete timeout ( so that there will be no data returned at all), but I guess then the screen will stay white forever ... 

What would be your preferred behavior in this case?

**Comment by JakobMiksch** [comment]
@dr-jts I pulled the latest commits from `master` and it still works as expected.

**Comment by dr-jts** [comment]
I prefer not to complicate the client code too much.  It's really just for demo purposes.  Most users will build their own client interface.

**Comment by JakobMiksch** [comment]
Alright, I understand. Then I am closing this PR.

**Pull request closed without merging**
